version: '3.8'

services:
  web:
    build: ./app/client
    ports:
      - "3000:3000"
    volumes:
        - ./app/client:/app/client
    depends_on:
        - api
  api:
    build: ./app/server
    ports:
      - "4200:4200"
    volumes:
        - ./app/server:/app/server
    depends_on:
        - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tableau-v2
volumes:
  postgres_data:
